# Generated by Django 6.0.5 on 2026-05-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_student_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together=set(),
        ),
    ]
